name: Generate Stats Cards

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stats Card
        uses: lowlighter/metrics@latest
        with:
          filename: stats.svg
          token: ${{ secrets.PAT_1 }}
          user: ahmedtaha100
          base: header, activity, community, repositories
          config_timezone: America/New_York

      - name: Languages Card
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.PAT_1 }}
          user: ahmedtaha100
          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage
          config_timezone: America/New_York
